theme: jekyll-theme-slate

title: FDC3 API specifications

description: The documentation website for the FINOS FDC3 API specifications

program_name: FDC3
program_link_url: finos.org/fdc3
program_image_url: https://www.finos.org/hs-fs/hubfs/FINOS/website/pages/programs/fdc3-logo.png

google_analytics: UU-123456

show_downloads: false

github:
  is_project_page: true
  repository_url: https://github.com/fdc3/api

version: '[[tag]]'

collections:
- tags

links:
  - name: Getting Started
    url: /
  - name: API specs
    url: /ts
  - name: FDC3 API Working Group
    url: https://finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/92963924/API+Working+Group
    target: _blank
  - name: FDC3 API Program
    url: https://finos.org/fdc3
    target: _blank

social_icons:
  - name: github
    image_url: "https://www.finos.org/hs-fs/hubfs/FINOS/website/logos/social-logos/github-logo-black.png?t=1539813516681&amp;width=48&amp;height=48&amp;name=github-logo.png"
    link_url: https://github.com/fdc3/api
  - name: confluence
    image_url: "https://www.finos.org/hs-fs/hubfs/sofin%20assets/External%20logos/atlassian-logo.png?width=48&amp;height=48&amp;name=atlassian-logo.png"
    link_url: https://finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/92963924/API+Working+Group
  - name: twitter
    image_url: "https://www.finos.org/hs-fs/hubfs/sofin%20assets/External%20logos/twitter-logo.png?width=48&amp;height=48&amp;name=twitter-logo.png"
    link_url: https://twitter.com/hashtag/fdc3